---

storage_directory: store/
api_tokens:
  - test1234

zigbee2mqtt:
  server: mqtt.server.tld
  port: 1883
  topic: zigbee2mqtt

http_worker:
  interval: 2

devices:
    office1:
      type: ikea_lamp
      zigbee_id: "0xDEWnioEEedeEIE"

    music_button:
      type: ikea_button
      zigbee_id: "0xAAA8043Dfednioe"
      actions:
        "toggle": radio
        "brightness_move_up": volumio_volume_up
        "brightness_move_down": volumio_volume_down
        #"brightness_step_up": spotify
        "brightness_step_down": radio_poweroff

    music_switch:
      type: mystrom_switch
      address: 192.168.2.2

    volumio:
      type: volumio
      address: 192.168.2.3

...
