---

storage_directory: store/
logfile: logfile.log
api_tokens:
  - test1234

metrics:
  render_api_base_url: http://graphite_server:8081
  server: graphite_server
  prefix: homeautomation
  timeout: 5

zigbee2mqtt:
  server: mqtt.server.tld
  port: 1883
  topic: zigbee2mqtt

http_worker:
  interval: 2

device_groups:
  temperature:
    devices:
      - temp1
      - temp2
    metrics:
      - temperature

devices:
    office1:
      metrics: true
      type: ikea_lamp
      zigbee_id: "0xDEWnioEEedeEIE"

    music_button:
      type: ikea_button
      zigbee_id: "0xAAA8043Dfednioe"
      scenes:
        "toggle": radio
        "brightness_move_up": volumio_volume_up
        "brightness_move_down": volumio_volume_down
        #"brightness_step_up": spotify
        "brightness_step_down": radio_poweroff

    music_switch:
      type: mystrom_switch
      address: 192.168.2.2

    volumio:
      type: volumio
      address: 192.168.2.3

...
